spring:
  profiles:
    include: oauth
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    username: root
    password: alsgur99
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_spring?useUnicode=true&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: spring-auth-project-spring-auth-project-spring-auth-project-spring-auth-project

cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
