spring:
  datasource:
    username: root
    password: alsgur99
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_spring?useUnicode=true&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
       hibernate:
        format_sql: true
    show-sql: true

